M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2025-08-18T22:10:58-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-18T22:10:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X123.325Y-88.5
X128.325Y-109.0
X168.325Y-109.0
X173.325Y-88.5
M30
