(part "SKRKAHE020"
    (packageRef "SKRKAEE020")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "688-SKRKAHE010")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Alps-Alpine/SKRKAHE020?qs=chTDxNqvsymUfAVYmcFXaw%3D%3D")
    (property "Manufacturer_Name" "ALPS Electric")
    (property "Manufacturer_Part_Number" "SKRKAHE020")
    (property "Description" "Tactile Switches 50 mAmps at 12 Volts")
    (property "Datasheet_Link" "https://www.alps.com/prod/info/E/HTML/Tact/SurfaceMount/SKRK/SKRKAHE020.html")
    (property "symbolName1" "SKRKAHE020")
)
