M48
; DRILL file {KiCad 7.0.7} date Sun Feb 18 14:41:30 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-18T14:41:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.813
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X187.998Y-95.036
X187.999Y-101.436
T2
X101.272Y-75.141
X101.272Y-122.541
X186.072Y-75.141
X186.272Y-122.541
T0
M30
