M48
; DRILL file {KiCad 9.0.2} date 2026-07-23T06:08:31-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T06:08:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X114.16Y-107.645
X119.94Y-107.645
T2
X99.5Y-84.95
X99.5Y-112.95
X187.5Y-84.95
X187.5Y-112.95
M30
